<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200420134219 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE translation (id INT AUTO_INCREMENT NOT NULL, key_id INT NOT NULL, locale_id INT NOT NULL, translation LONGTEXT DEFAULT NULL, INDEX IDX_B469456FD145533 (key_id), INDEX IDX_B469456FE559DFD1 (locale_id), UNIQUE INDEX translation_unique (key_id, locale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation__locale (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(2) NOT NULL, UNIQUE INDEX translation_locale_unique (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation__domain (id INT AUTO_INCREMENT NOT NULL, domain VARCHAR(255) NOT NULL, UNIQUE INDEX translation_domain_unique (domain), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation__shared (id INT AUTO_INCREMENT NOT NULL, locale_id INT NOT NULL, domain_id INT NOT NULL, is_shared TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_4BB3EACAE559DFD1 (locale_id), INDEX IDX_4BB3EACA115F0EE5 (domain_id), UNIQUE INDEX translation_shared_unique (locale_id, domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translation__key (id INT AUTO_INCREMENT NOT NULL, domain_id INT NOT NULL, trans_key VARCHAR(255) NOT NULL, INDEX IDX_EAD911C8115F0EE5 (domain_id), UNIQUE INDEX translation_key_unique (domain_id, trans_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device__promotion_visit (id INT AUTO_INCREMENT NOT NULL, page_id INT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_80A5FFF2C4663E4 (page_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, locale_id INT NOT NULL, username VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, date_format INT DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATE DEFAULT NULL, enabled TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATE NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D649E559DFD1 (locale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device__page_views (id INT AUTO_INCREMENT NOT NULL, device_id INT NOT NULL, module_id INT DEFAULT NULL, url VARCHAR(255) NOT NULL, page VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_66BAC7EF94A4C7D4 (device_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user__device (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, ip VARCHAR(15) DEFAULT NULL, is_computer TINYINT(1) NOT NULL, os VARCHAR(30) NOT NULL, browser VARCHAR(30) NOT NULL, browser_version VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_A8114F07A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE master__posts (id INT AUTO_INCREMENT NOT NULL, thumb_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, slug VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_F385F1482B36786B (title), INDEX IDX_F385F148C7034EA5 (thumb_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE master__email (id INT AUTO_INCREMENT NOT NULL, automated_id INT DEFAULT NULL, subject VARCHAR(255) NOT NULL, text TEXT NOT NULL, is_draft TINYINT(1) NOT NULL, in_process TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_9C4A37C6B1254A89 (automated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE master__email_recipient (id INT AUTO_INCREMENT NOT NULL, email_id INT NOT NULL, client_id INT NOT NULL, email_address VARCHAR(50) NOT NULL, is_delivered TINYINT(1) NOT NULL, is_opened TINYINT(1) NOT NULL, is_clicked TINYINT(1) NOT NULL, is_bounced TINYINT(1) NOT NULL, INDEX IDX_8A5C4BC4A832C1C9 (email_id), INDEX IDX_8A5C4BC419EB6921 (client_id), UNIQUE INDEX master_email_recipient (email_id, client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE master__email_automated (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, text TEXT NOT NULL, type INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__settings (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, module INT NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, INDEX IDX_20A535AA19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__team (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_3AA84AB319EB6921 (client_id), UNIQUE INDEX UNIQ_3AA84AB3A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__subscription (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, amount NUMERIC(8, 2) NOT NULL, INDEX IDX_8E2B3C4E19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__payment_settings (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, method INT NOT NULL, is_active TINYINT(1) NOT NULL, description TEXT DEFAULT NULL, INDEX IDX_2609750819EB6921 (client_id), UNIQUE INDEX member_unique (client_id, method), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__posts (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, thumb_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, slug VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_57C31DD52B36786B (title), INDEX IDX_57C31DD519EB6921 (client_id), INDEX IDX_57C31DD5C7034EA5 (thumb_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__referral (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, affiliate_id INT NOT NULL, is_paid TINYINT(1) NOT NULL, created_at DATE NOT NULL, UNIQUE INDEX UNIQ_B6E7086F19EB6921 (client_id), INDEX IDX_B6E7086F9F12C49A (affiliate_id), UNIQUE INDEX referral_unique (client_id, affiliate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification__notify (id INT AUTO_INCREMENT NOT NULL, notification_id INT DEFAULT NULL, user_id INT DEFAULT NULL, seen TINYINT(1) NOT NULL, INDEX IDX_CD5680FCEF1A9D84 (notification_id), INDEX IDX_CD5680FCA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(4000) NOT NULL, message VARCHAR(4000) DEFAULT NULL, link VARCHAR(4000) DEFAULT NULL, module_id INT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__module_access (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, module_id INT NOT NULL, expired_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, status INT NOT NULL, INDEX IDX_22F969DA19EB6921 (client_id), UNIQUE INDEX access_unique (client_id, module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__merchant (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, merchant VARCHAR(1) NOT NULL, merchant_key VARCHAR(255) NOT NULL, merchant_pin VARCHAR(4) DEFAULT NULL, currency VARCHAR(3) NOT NULL, is_sandbox TINYINT(1) NOT NULL, INDEX IDX_B14BB08E19EB6921 (client_id), UNIQUE INDEX merchant_unique (client_id, merchant), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__affiliate (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, email VARCHAR(25) DEFAULT NULL, referral_code VARCHAR(20) NOT NULL, created_at DATE NOT NULL, UNIQUE INDEX UNIQ_84B2399319EB6921 (client_id), UNIQUE INDEX affiliate_unique (name, email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(50) DEFAULT NULL, level INT NOT NULL, weight_format INT NOT NULL, currency INT NOT NULL, country VARCHAR(2) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, region INT DEFAULT NULL, city INT DEFAULT NULL, timezone VARCHAR(30) DEFAULT NULL, delivery_price NUMERIC(7, 2) NOT NULL, order_time VARCHAR(255) DEFAULT NULL, same_day_orders TINYINT(1) NOT NULL, token VARCHAR(30) NOT NULL, created_at DATE NOT NULL, UNIQUE INDEX UNIQ_C74404555E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__vendor_orders (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, vendor_id INT DEFAULT NULL, order_date DATE NOT NULL, INDEX IDX_A5D88E9819EB6921 (client_id), INDEX IDX_A5D88E98F603EE73 (vendor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__payment_method (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, gardener_price INT NOT NULL, farmer_price INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share__suspended_weeks (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, week INT NOT NULL, year INT NOT NULL, INDEX IDX_5A20DD0519EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__transactions (id INT AUTO_INCREMENT NOT NULL, payment_method INT NOT NULL, payment_id INT DEFAULT NULL, transaction_status INT NOT NULL, payment_code VARCHAR(255) NOT NULL, wallet VARCHAR(255) NOT NULL, invoice VARCHAR(255) NOT NULL, amount BIGINT NOT NULL, created_at DATETIME NOT NULL, confirmed_at DATETIME DEFAULT NULL, INDEX IDX_D49608E67B61A1F6 (payment_method), UNIQUE INDEX UNIQ_D49608E64C3A3BB (payment_id), INDEX IDX_D49608E6D7D175C (transaction_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share__pickups (id INT AUTO_INCREMENT NOT NULL, share_id INT DEFAULT NULL, date DATE NOT NULL, skipped TINYINT(1) NOT NULL, is_suspended TINYINT(1) NOT NULL, INDEX IDX_55F08D2B2AE63FDB (share_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share__custom (id INT AUTO_INCREMENT NOT NULL, share_product_id INT DEFAULT NULL, product_id INT DEFAULT NULL, share_id INT DEFAULT NULL, INDEX IDX_4EDB5B84A1615E9C (share_product_id), INDEX IDX_4EDB5B844584665A (product_id), INDEX IDX_4EDB5B842AE63FDB (share_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pos__product (id INT AUTO_INCREMENT NOT NULL, pos_id INT NOT NULL, product_id INT DEFAULT NULL, price NUMERIC(7, 2) NOT NULL, weight NUMERIC(7, 2) DEFAULT NULL, qty INT DEFAULT NULL, INDEX IDX_EE06AFE041085FAE (pos_id), INDEX IDX_EE06AFE04584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__notifies (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, notify_type INT NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_D4DC51699395C3F3 (customer_id), UNIQUE INDEX customer_emails_unique (customer_id, notify_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pos__products (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, image INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, price NUMERIC(7, 2) NOT NULL, delivery_price NUMERIC(7, 2) DEFAULT NULL, category INT DEFAULT NULL, weight NUMERIC(7, 2) DEFAULT NULL, sku VARCHAR(16) DEFAULT NULL, pay_by_item TINYINT(1) NOT NULL, is_pos TINYINT(1) NOT NULL, INDEX IDX_BBEA2BDC19EB6921 (client_id), INDEX IDX_BBEA2BDCC53D045F (image), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__vendor (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, address_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, category LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', order_day LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', is_active TINYINT(1) NOT NULL, INDEX IDX_10CC70CB19EB6921 (client_id), UNIQUE INDEX UNIQ_10CC70CBF5B7AF75 (address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__address (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, apartment VARCHAR(255) DEFAULT NULL, postalCode VARCHAR(5) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, type INT NOT NULL, INDEX IDX_55C3CDD39395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client__tags (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, name VARCHAR(191) NOT NULL, INDEX IDX_91F4788A19EB6921 (client_id), UNIQUE INDEX tags_unique (client_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__referrals (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, referral_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_AB286D099395C3F3 (customer_id), UNIQUE INDEX UNIQ_AB286D093CCAA4B7 (referral_id), UNIQUE INDEX customer_referral_unique (customer_id, referral_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__renewal_views (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, customer_id INT DEFAULT NULL, ip INT UNSIGNED DEFAULT NULL, step INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_88E36BAB19EB6921 (client_id), INDEX IDX_88E36BAB9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__orders (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, share_id INT DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, INDEX IDX_C1BED319EB6921 (client_id), INDEX IDX_C1BED32AE63FDB (share_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__vendor_contact (id INT AUTO_INCREMENT NOT NULL, vendor_id INT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, token VARCHAR(50) NOT NULL, notify_enabled TINYINT(1) NOT NULL, INDEX IDX_F544C542F603EE73 (vendor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__payments (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, transaction_id INT DEFAULT NULL, amount NUMERIC(8, 2) NOT NULL, shares LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_E0EF26489395C3F3 (customer_id), UNIQUE INDEX UNIQ_E0EF26482FC0CB0F (transaction_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, firstname VARCHAR(25) NOT NULL, lastname VARCHAR(25) NOT NULL, email VARCHAR(50) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, delivery_day INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at DATE NOT NULL, token VARCHAR(50) NOT NULL, is_lead TINYINT(1) NOT NULL, is_activated TINYINT(1) NOT NULL, testimonial TEXT DEFAULT NULL, INDEX IDX_81398E0919EB6921 (client_id), UNIQUE INDEX customer_unique (client_id, email), UNIQUE INDEX customer_phone_unique (client_id, phone), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__transaction_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__product__tag (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, client_id INT DEFAULT NULL, INDEX IDX_FD349E724584665A (product_id), INDEX IDX_FD349E7219EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__invoice (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, location_id INT DEFAULT NULL, amount NUMERIC(8, 2) NOT NULL, ref_num VARCHAR(255) DEFAULT NULL, order_date DATE NOT NULL, is_paid TINYINT(1) NOT NULL, is_sent TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_C8E8B5169395C3F3 (customer_id), INDEX IDX_C8E8B51664D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__invoice_product (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, share_id INT DEFAULT NULL, product_id INT DEFAULT NULL, qty INT DEFAULT NULL, weight NUMERIC(7, 2) DEFAULT NULL, total_amount NUMERIC(8, 2) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_4CE9878E2989F1FD (invoice_id), INDEX IDX_4CE9878E2AE63FDB (share_id), INDEX IDX_4CE9878E4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pos (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, total NUMERIC(7, 2) NOT NULL, received_amount NUMERIC(7, 2) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_80D9E6AC19EB6921 (client_id), INDEX IDX_80D9E6AC9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__location (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, name VARCHAR(255) NOT NULL, street VARCHAR(255) DEFAULT NULL, apartment INT DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, postalCode INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, type INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATE NOT NULL, INDEX IDX_DBA334B119EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__location_workdays (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, weekday INT NOT NULL, start_time VARCHAR(8) DEFAULT NULL, duration INT DEFAULT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_A2035B2664D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, price NUMERIC(8, 2) NOT NULL, is_active TINYINT(1) NOT NULL, updated_at DATE DEFAULT NULL, INDEX IDX_EF069D5A19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share__products (id INT AUTO_INCREMENT NOT NULL, customer_order INT DEFAULT NULL, vendor_order INT DEFAULT NULL, product_id INT DEFAULT NULL, price NUMERIC(7, 2) NOT NULL, weight NUMERIC(7, 2) NOT NULL, qty INT NOT NULL, INDEX IDX_768DD2B63B1CE6A3 (customer_order), INDEX IDX_768DD2B6E36F91D8 (vendor_order), INDEX IDX_768DD2B64584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE share__customer (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, share_id INT NOT NULL, location INT DEFAULT NULL, type INT NOT NULL, status INT NOT NULL, start_date DATE NOT NULL, pickups_num INT NOT NULL, renewal_date DATE NOT NULL, pickup_day INT DEFAULT NULL, INDEX IDX_440E06E59395C3F3 (customer_id), INDEX IDX_440E06E52AE63FDB (share_id), INDEX IDX_440E06E55E9E89CB (location), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email__testimonial_recipient (id INT AUTO_INCREMENT NOT NULL, affiliate_id INT DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, firstname VARCHAR(25) NOT NULL, lastname VARCHAR(25) NOT NULL, message TEXT DEFAULT NULL, INDEX IDX_7DDB49AF9F12C49A (affiliate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email__recipient (id INT AUTO_INCREMENT NOT NULL, log_id INT NOT NULL, customer_id INT DEFAULT NULL, email_address VARCHAR(50) NOT NULL, is_delivered TINYINT(1) NOT NULL, is_opened TINYINT(1) NOT NULL, is_clicked TINYINT(1) NOT NULL, is_bounced TINYINT(1) NOT NULL, INDEX IDX_892BA88BEA675D86 (log_id), INDEX IDX_892BA88B9395C3F3 (customer_id), UNIQUE INDEX customer_email_recipient (log_id, customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email__log (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, automated_id INT DEFAULT NULL, reply_email VARCHAR(50) NOT NULL, reply_name VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, text TEXT NOT NULL, is_draft TINYINT(1) NOT NULL, in_process TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_5D6251BA19EB6921 (client_id), INDEX IDX_5D6251BAB1254A89 (automated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email__feedback (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, share_id INT DEFAULT NULL, recipient_id INT DEFAULT NULL, is_satisfied TINYINT(1) NOT NULL, share_date DATE NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_F3E29E139395C3F3 (customer_id), INDEX IDX_F3E29E132AE63FDB (share_id), UNIQUE INDEX UNIQ_F3E29E13E92F8F78 (recipient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email__auto (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, subject VARCHAR(255) NOT NULL, text TEXT NOT NULL, type INT NOT NULL, INDEX IDX_A6D2146E19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__image (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, size INT NOT NULL, mime_type VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F37C721D19EB6921 (client_id), UNIQUE INDEX client_image_unique (client_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456FD145533 FOREIGN KEY (key_id) REFERENCES translation__key (id)');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456FE559DFD1 FOREIGN KEY (locale_id) REFERENCES translation__locale (id)');
        $this->addSql('ALTER TABLE translation__shared ADD CONSTRAINT FK_4BB3EACAE559DFD1 FOREIGN KEY (locale_id) REFERENCES translation__locale (id)');
        $this->addSql('ALTER TABLE translation__shared ADD CONSTRAINT FK_4BB3EACA115F0EE5 FOREIGN KEY (domain_id) REFERENCES translation__domain (id)');
        $this->addSql('ALTER TABLE translation__key ADD CONSTRAINT FK_EAD911C8115F0EE5 FOREIGN KEY (domain_id) REFERENCES translation__domain (id)');
        $this->addSql('ALTER TABLE device__promotion_visit ADD CONSTRAINT FK_80A5FFF2C4663E4 FOREIGN KEY (page_id) REFERENCES device__page_views (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E559DFD1 FOREIGN KEY (locale_id) REFERENCES translation__locale (id)');
        $this->addSql('ALTER TABLE device__page_views ADD CONSTRAINT FK_66BAC7EF94A4C7D4 FOREIGN KEY (device_id) REFERENCES user__device (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user__device ADD CONSTRAINT FK_A8114F07A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE master__posts ADD CONSTRAINT FK_F385F148C7034EA5 FOREIGN KEY (thumb_id) REFERENCES media__image (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE master__email ADD CONSTRAINT FK_9C4A37C6B1254A89 FOREIGN KEY (automated_id) REFERENCES master__email_automated (id)');
        $this->addSql('ALTER TABLE master__email_recipient ADD CONSTRAINT FK_8A5C4BC4A832C1C9 FOREIGN KEY (email_id) REFERENCES master__email (id)');
        $this->addSql('ALTER TABLE master__email_recipient ADD CONSTRAINT FK_8A5C4BC419EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client__settings ADD CONSTRAINT FK_20A535AA19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client__team ADD CONSTRAINT FK_3AA84AB319EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client__team ADD CONSTRAINT FK_3AA84AB3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE client__subscription ADD CONSTRAINT FK_8E2B3C4E19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client__payment_settings ADD CONSTRAINT FK_2609750819EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client__posts ADD CONSTRAINT FK_57C31DD519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client__posts ADD CONSTRAINT FK_57C31DD5C7034EA5 FOREIGN KEY (thumb_id) REFERENCES media__image (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE client__referral ADD CONSTRAINT FK_B6E7086F19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client__referral ADD CONSTRAINT FK_B6E7086F9F12C49A FOREIGN KEY (affiliate_id) REFERENCES client__affiliate (id)');
        $this->addSql('ALTER TABLE notification__notify ADD CONSTRAINT FK_CD5680FCEF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id)');
        $this->addSql('ALTER TABLE notification__notify ADD CONSTRAINT FK_CD5680FCA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE client__module_access ADD CONSTRAINT FK_22F969DA19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client__merchant ADD CONSTRAINT FK_B14BB08E19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client__affiliate ADD CONSTRAINT FK_84B2399319EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE customer__vendor_orders ADD CONSTRAINT FK_A5D88E9819EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__vendor_orders ADD CONSTRAINT FK_A5D88E98F603EE73 FOREIGN KEY (vendor_id) REFERENCES customer__vendor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE share__suspended_weeks ADD CONSTRAINT FK_5A20DD0519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__transactions ADD CONSTRAINT FK_D49608E67B61A1F6 FOREIGN KEY (payment_method) REFERENCES customer__payment_method (id)');
        $this->addSql('ALTER TABLE customer__transactions ADD CONSTRAINT FK_D49608E64C3A3BB FOREIGN KEY (payment_id) REFERENCES customer__payments (id)');
        $this->addSql('ALTER TABLE customer__transactions ADD CONSTRAINT FK_D49608E6D7D175C FOREIGN KEY (transaction_status) REFERENCES customer__transaction_status (id)');
        $this->addSql('ALTER TABLE share__pickups ADD CONSTRAINT FK_55F08D2B2AE63FDB FOREIGN KEY (share_id) REFERENCES share__customer (id)');
        $this->addSql('ALTER TABLE share__custom ADD CONSTRAINT FK_4EDB5B84A1615E9C FOREIGN KEY (share_product_id) REFERENCES share__products (id)');
        $this->addSql('ALTER TABLE share__custom ADD CONSTRAINT FK_4EDB5B844584665A FOREIGN KEY (product_id) REFERENCES pos__products (id)');
        $this->addSql('ALTER TABLE share__custom ADD CONSTRAINT FK_4EDB5B842AE63FDB FOREIGN KEY (share_id) REFERENCES share__customer (id)');
        $this->addSql('ALTER TABLE pos__product ADD CONSTRAINT FK_EE06AFE041085FAE FOREIGN KEY (pos_id) REFERENCES pos (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pos__product ADD CONSTRAINT FK_EE06AFE04584665A FOREIGN KEY (product_id) REFERENCES pos__products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__notifies ADD CONSTRAINT FK_D4DC51699395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE pos__products ADD CONSTRAINT FK_BBEA2BDC19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pos__products ADD CONSTRAINT FK_BBEA2BDCC53D045F FOREIGN KEY (image) REFERENCES media__image (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE customer__vendor ADD CONSTRAINT FK_10CC70CB19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE customer__vendor ADD CONSTRAINT FK_10CC70CBF5B7AF75 FOREIGN KEY (address_id) REFERENCES customer__address (id)');
        $this->addSql('ALTER TABLE customer__address ADD CONSTRAINT FK_55C3CDD39395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE client__tags ADD CONSTRAINT FK_91F4788A19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__referrals ADD CONSTRAINT FK_AB286D099395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE customer__referrals ADD CONSTRAINT FK_AB286D093CCAA4B7 FOREIGN KEY (referral_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE customer__renewal_views ADD CONSTRAINT FK_88E36BAB19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE customer__renewal_views ADD CONSTRAINT FK_88E36BAB9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE customer__orders ADD CONSTRAINT FK_C1BED319EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__orders ADD CONSTRAINT FK_C1BED32AE63FDB FOREIGN KEY (share_id) REFERENCES share (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__vendor_contact ADD CONSTRAINT FK_F544C542F603EE73 FOREIGN KEY (vendor_id) REFERENCES customer__vendor (id)');
        $this->addSql('ALTER TABLE customer__payments ADD CONSTRAINT FK_E0EF26489395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE customer__payments ADD CONSTRAINT FK_E0EF26482FC0CB0F FOREIGN KEY (transaction_id) REFERENCES customer__transactions (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E0919EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE customer__product__tag ADD CONSTRAINT FK_FD349E724584665A FOREIGN KEY (product_id) REFERENCES pos__products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__product__tag ADD CONSTRAINT FK_FD349E7219EB6921 FOREIGN KEY (client_id) REFERENCES client__tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__invoice ADD CONSTRAINT FK_C8E8B5169395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE customer__invoice ADD CONSTRAINT FK_C8E8B51664D218E FOREIGN KEY (location_id) REFERENCES customer__location (id)');
        $this->addSql('ALTER TABLE customer__invoice_product ADD CONSTRAINT FK_4CE9878E2989F1FD FOREIGN KEY (invoice_id) REFERENCES customer__invoice (id)');
        $this->addSql('ALTER TABLE customer__invoice_product ADD CONSTRAINT FK_4CE9878E2AE63FDB FOREIGN KEY (share_id) REFERENCES share (id)');
        $this->addSql('ALTER TABLE customer__invoice_product ADD CONSTRAINT FK_4CE9878E4584665A FOREIGN KEY (product_id) REFERENCES pos__products (id)');
        $this->addSql('ALTER TABLE pos ADD CONSTRAINT FK_80D9E6AC19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pos ADD CONSTRAINT FK_80D9E6AC9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__location ADD CONSTRAINT FK_DBA334B119EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE customer__location_workdays ADD CONSTRAINT FK_A2035B2664D218E FOREIGN KEY (location_id) REFERENCES customer__location (id)');
        $this->addSql('ALTER TABLE share ADD CONSTRAINT FK_EF069D5A19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE share__products ADD CONSTRAINT FK_768DD2B63B1CE6A3 FOREIGN KEY (customer_order) REFERENCES customer__orders (id)');
        $this->addSql('ALTER TABLE share__products ADD CONSTRAINT FK_768DD2B6E36F91D8 FOREIGN KEY (vendor_order) REFERENCES customer__vendor_orders (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE share__products ADD CONSTRAINT FK_768DD2B64584665A FOREIGN KEY (product_id) REFERENCES pos__products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE share__customer ADD CONSTRAINT FK_440E06E59395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE share__customer ADD CONSTRAINT FK_440E06E52AE63FDB FOREIGN KEY (share_id) REFERENCES share (id)');
        $this->addSql('ALTER TABLE share__customer ADD CONSTRAINT FK_440E06E55E9E89CB FOREIGN KEY (location) REFERENCES customer__location (id)');
        $this->addSql('ALTER TABLE email__testimonial_recipient ADD CONSTRAINT FK_7DDB49AF9F12C49A FOREIGN KEY (affiliate_id) REFERENCES customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE email__recipient ADD CONSTRAINT FK_892BA88BEA675D86 FOREIGN KEY (log_id) REFERENCES email__log (id)');
        $this->addSql('ALTER TABLE email__recipient ADD CONSTRAINT FK_892BA88B9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE email__log ADD CONSTRAINT FK_5D6251BA19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE email__log ADD CONSTRAINT FK_5D6251BAB1254A89 FOREIGN KEY (automated_id) REFERENCES email__auto (id)');
        $this->addSql('ALTER TABLE email__feedback ADD CONSTRAINT FK_F3E29E139395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE email__feedback ADD CONSTRAINT FK_F3E29E132AE63FDB FOREIGN KEY (share_id) REFERENCES share (id)');
        $this->addSql('ALTER TABLE email__feedback ADD CONSTRAINT FK_F3E29E13E92F8F78 FOREIGN KEY (recipient_id) REFERENCES email__recipient (id)');
        $this->addSql('ALTER TABLE email__auto ADD CONSTRAINT FK_A6D2146E19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE media__image ADD CONSTRAINT FK_F37C721D19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE translation DROP FOREIGN KEY FK_B469456FE559DFD1');
        $this->addSql('ALTER TABLE translation__shared DROP FOREIGN KEY FK_4BB3EACAE559DFD1');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649E559DFD1');
        $this->addSql('ALTER TABLE translation__shared DROP FOREIGN KEY FK_4BB3EACA115F0EE5');
        $this->addSql('ALTER TABLE translation__key DROP FOREIGN KEY FK_EAD911C8115F0EE5');
        $this->addSql('ALTER TABLE translation DROP FOREIGN KEY FK_B469456FD145533');
        $this->addSql('ALTER TABLE user__device DROP FOREIGN KEY FK_A8114F07A76ED395');
        $this->addSql('ALTER TABLE client__team DROP FOREIGN KEY FK_3AA84AB3A76ED395');
        $this->addSql('ALTER TABLE notification__notify DROP FOREIGN KEY FK_CD5680FCA76ED395');
        $this->addSql('ALTER TABLE device__promotion_visit DROP FOREIGN KEY FK_80A5FFF2C4663E4');
        $this->addSql('ALTER TABLE device__page_views DROP FOREIGN KEY FK_66BAC7EF94A4C7D4');
        $this->addSql('ALTER TABLE master__email_recipient DROP FOREIGN KEY FK_8A5C4BC4A832C1C9');
        $this->addSql('ALTER TABLE master__email DROP FOREIGN KEY FK_9C4A37C6B1254A89');
        $this->addSql('ALTER TABLE notification__notify DROP FOREIGN KEY FK_CD5680FCEF1A9D84');
        $this->addSql('ALTER TABLE client__referral DROP FOREIGN KEY FK_B6E7086F9F12C49A');
        $this->addSql('ALTER TABLE master__email_recipient DROP FOREIGN KEY FK_8A5C4BC419EB6921');
        $this->addSql('ALTER TABLE client__settings DROP FOREIGN KEY FK_20A535AA19EB6921');
        $this->addSql('ALTER TABLE client__team DROP FOREIGN KEY FK_3AA84AB319EB6921');
        $this->addSql('ALTER TABLE client__subscription DROP FOREIGN KEY FK_8E2B3C4E19EB6921');
        $this->addSql('ALTER TABLE client__payment_settings DROP FOREIGN KEY FK_2609750819EB6921');
        $this->addSql('ALTER TABLE client__posts DROP FOREIGN KEY FK_57C31DD519EB6921');
        $this->addSql('ALTER TABLE client__referral DROP FOREIGN KEY FK_B6E7086F19EB6921');
        $this->addSql('ALTER TABLE client__module_access DROP FOREIGN KEY FK_22F969DA19EB6921');
        $this->addSql('ALTER TABLE client__merchant DROP FOREIGN KEY FK_B14BB08E19EB6921');
        $this->addSql('ALTER TABLE client__affiliate DROP FOREIGN KEY FK_84B2399319EB6921');
        $this->addSql('ALTER TABLE customer__vendor_orders DROP FOREIGN KEY FK_A5D88E9819EB6921');
        $this->addSql('ALTER TABLE share__suspended_weeks DROP FOREIGN KEY FK_5A20DD0519EB6921');
        $this->addSql('ALTER TABLE pos__products DROP FOREIGN KEY FK_BBEA2BDC19EB6921');
        $this->addSql('ALTER TABLE customer__vendor DROP FOREIGN KEY FK_10CC70CB19EB6921');
        $this->addSql('ALTER TABLE client__tags DROP FOREIGN KEY FK_91F4788A19EB6921');
        $this->addSql('ALTER TABLE customer__renewal_views DROP FOREIGN KEY FK_88E36BAB19EB6921');
        $this->addSql('ALTER TABLE customer__orders DROP FOREIGN KEY FK_C1BED319EB6921');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E0919EB6921');
        $this->addSql('ALTER TABLE pos DROP FOREIGN KEY FK_80D9E6AC19EB6921');
        $this->addSql('ALTER TABLE customer__location DROP FOREIGN KEY FK_DBA334B119EB6921');
        $this->addSql('ALTER TABLE share DROP FOREIGN KEY FK_EF069D5A19EB6921');
        $this->addSql('ALTER TABLE email__log DROP FOREIGN KEY FK_5D6251BA19EB6921');
        $this->addSql('ALTER TABLE email__auto DROP FOREIGN KEY FK_A6D2146E19EB6921');
        $this->addSql('ALTER TABLE media__image DROP FOREIGN KEY FK_F37C721D19EB6921');
        $this->addSql('ALTER TABLE share__products DROP FOREIGN KEY FK_768DD2B6E36F91D8');
        $this->addSql('ALTER TABLE customer__transactions DROP FOREIGN KEY FK_D49608E67B61A1F6');
        $this->addSql('ALTER TABLE customer__payments DROP FOREIGN KEY FK_E0EF26482FC0CB0F');
        $this->addSql('ALTER TABLE share__custom DROP FOREIGN KEY FK_4EDB5B844584665A');
        $this->addSql('ALTER TABLE pos__product DROP FOREIGN KEY FK_EE06AFE04584665A');
        $this->addSql('ALTER TABLE customer__product__tag DROP FOREIGN KEY FK_FD349E724584665A');
        $this->addSql('ALTER TABLE customer__invoice_product DROP FOREIGN KEY FK_4CE9878E4584665A');
        $this->addSql('ALTER TABLE share__products DROP FOREIGN KEY FK_768DD2B64584665A');
        $this->addSql('ALTER TABLE customer__vendor_orders DROP FOREIGN KEY FK_A5D88E98F603EE73');
        $this->addSql('ALTER TABLE customer__vendor_contact DROP FOREIGN KEY FK_F544C542F603EE73');
        $this->addSql('ALTER TABLE customer__vendor DROP FOREIGN KEY FK_10CC70CBF5B7AF75');
        $this->addSql('ALTER TABLE customer__product__tag DROP FOREIGN KEY FK_FD349E7219EB6921');
        $this->addSql('ALTER TABLE share__products DROP FOREIGN KEY FK_768DD2B63B1CE6A3');
        $this->addSql('ALTER TABLE customer__transactions DROP FOREIGN KEY FK_D49608E64C3A3BB');
        $this->addSql('ALTER TABLE customer__notifies DROP FOREIGN KEY FK_D4DC51699395C3F3');
        $this->addSql('ALTER TABLE customer__address DROP FOREIGN KEY FK_55C3CDD39395C3F3');
        $this->addSql('ALTER TABLE customer__referrals DROP FOREIGN KEY FK_AB286D099395C3F3');
        $this->addSql('ALTER TABLE customer__referrals DROP FOREIGN KEY FK_AB286D093CCAA4B7');
        $this->addSql('ALTER TABLE customer__renewal_views DROP FOREIGN KEY FK_88E36BAB9395C3F3');
        $this->addSql('ALTER TABLE customer__payments DROP FOREIGN KEY FK_E0EF26489395C3F3');
        $this->addSql('ALTER TABLE customer__invoice DROP FOREIGN KEY FK_C8E8B5169395C3F3');
        $this->addSql('ALTER TABLE pos DROP FOREIGN KEY FK_80D9E6AC9395C3F3');
        $this->addSql('ALTER TABLE share__customer DROP FOREIGN KEY FK_440E06E59395C3F3');
        $this->addSql('ALTER TABLE email__testimonial_recipient DROP FOREIGN KEY FK_7DDB49AF9F12C49A');
        $this->addSql('ALTER TABLE email__recipient DROP FOREIGN KEY FK_892BA88B9395C3F3');
        $this->addSql('ALTER TABLE email__feedback DROP FOREIGN KEY FK_F3E29E139395C3F3');
        $this->addSql('ALTER TABLE customer__transactions DROP FOREIGN KEY FK_D49608E6D7D175C');
        $this->addSql('ALTER TABLE customer__invoice_product DROP FOREIGN KEY FK_4CE9878E2989F1FD');
        $this->addSql('ALTER TABLE pos__product DROP FOREIGN KEY FK_EE06AFE041085FAE');
        $this->addSql('ALTER TABLE customer__invoice DROP FOREIGN KEY FK_C8E8B51664D218E');
        $this->addSql('ALTER TABLE customer__location_workdays DROP FOREIGN KEY FK_A2035B2664D218E');
        $this->addSql('ALTER TABLE share__customer DROP FOREIGN KEY FK_440E06E55E9E89CB');
        $this->addSql('ALTER TABLE customer__orders DROP FOREIGN KEY FK_C1BED32AE63FDB');
        $this->addSql('ALTER TABLE customer__invoice_product DROP FOREIGN KEY FK_4CE9878E2AE63FDB');
        $this->addSql('ALTER TABLE share__customer DROP FOREIGN KEY FK_440E06E52AE63FDB');
        $this->addSql('ALTER TABLE email__feedback DROP FOREIGN KEY FK_F3E29E132AE63FDB');
        $this->addSql('ALTER TABLE share__custom DROP FOREIGN KEY FK_4EDB5B84A1615E9C');
        $this->addSql('ALTER TABLE share__pickups DROP FOREIGN KEY FK_55F08D2B2AE63FDB');
        $this->addSql('ALTER TABLE share__custom DROP FOREIGN KEY FK_4EDB5B842AE63FDB');
        $this->addSql('ALTER TABLE email__feedback DROP FOREIGN KEY FK_F3E29E13E92F8F78');
        $this->addSql('ALTER TABLE email__recipient DROP FOREIGN KEY FK_892BA88BEA675D86');
        $this->addSql('ALTER TABLE email__log DROP FOREIGN KEY FK_5D6251BAB1254A89');
        $this->addSql('ALTER TABLE master__posts DROP FOREIGN KEY FK_F385F148C7034EA5');
        $this->addSql('ALTER TABLE client__posts DROP FOREIGN KEY FK_57C31DD5C7034EA5');
        $this->addSql('ALTER TABLE pos__products DROP FOREIGN KEY FK_BBEA2BDCC53D045F');
        $this->addSql('DROP TABLE translation');
        $this->addSql('DROP TABLE translation__locale');
        $this->addSql('DROP TABLE translation__domain');
        $this->addSql('DROP TABLE translation__shared');
        $this->addSql('DROP TABLE translation__key');
        $this->addSql('DROP TABLE device__promotion_visit');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE device__page_views');
        $this->addSql('DROP TABLE user__device');
        $this->addSql('DROP TABLE master__posts');
        $this->addSql('DROP TABLE master__email');
        $this->addSql('DROP TABLE master__email_recipient');
        $this->addSql('DROP TABLE master__email_automated');
        $this->addSql('DROP TABLE client__settings');
        $this->addSql('DROP TABLE client__team');
        $this->addSql('DROP TABLE client__subscription');
        $this->addSql('DROP TABLE client__payment_settings');
        $this->addSql('DROP TABLE client__posts');
        $this->addSql('DROP TABLE client__referral');
        $this->addSql('DROP TABLE notification__notify');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE client__module_access');
        $this->addSql('DROP TABLE client__merchant');
        $this->addSql('DROP TABLE client__affiliate');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE customer__vendor_orders');
        $this->addSql('DROP TABLE customer__payment_method');
        $this->addSql('DROP TABLE share__suspended_weeks');
        $this->addSql('DROP TABLE customer__transactions');
        $this->addSql('DROP TABLE share__pickups');
        $this->addSql('DROP TABLE share__custom');
        $this->addSql('DROP TABLE pos__product');
        $this->addSql('DROP TABLE customer__notifies');
        $this->addSql('DROP TABLE pos__products');
        $this->addSql('DROP TABLE customer__vendor');
        $this->addSql('DROP TABLE customer__address');
        $this->addSql('DROP TABLE client__tags');
        $this->addSql('DROP TABLE customer__referrals');
        $this->addSql('DROP TABLE customer__renewal_views');
        $this->addSql('DROP TABLE customer__orders');
        $this->addSql('DROP TABLE customer__vendor_contact');
        $this->addSql('DROP TABLE customer__payments');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE customer__transaction_status');
        $this->addSql('DROP TABLE customer__product__tag');
        $this->addSql('DROP TABLE customer__invoice');
        $this->addSql('DROP TABLE customer__invoice_product');
        $this->addSql('DROP TABLE pos');
        $this->addSql('DROP TABLE customer__location');
        $this->addSql('DROP TABLE customer__location_workdays');
        $this->addSql('DROP TABLE share');
        $this->addSql('DROP TABLE share__products');
        $this->addSql('DROP TABLE share__customer');
        $this->addSql('DROP TABLE email__testimonial_recipient');
        $this->addSql('DROP TABLE email__recipient');
        $this->addSql('DROP TABLE email__log');
        $this->addSql('DROP TABLE email__feedback');
        $this->addSql('DROP TABLE email__auto');
        $this->addSql('DROP TABLE media__image');
    }
}
